output_path: .peak
port: 1111
index: index.html

watch:
  blog: 'generalassemblygrdunn'
  email: ''
  password: ''
  index: 'index.html'
  compiler:
    url: 'http://generalassemblygrdunn.tumblr.com/'

deploy:
  blog: 'generalassemblygrdunn'
  email: ''
  password: ''
  index: 'index.html'
  compiler:
    url: 'http://generalassemblygrdunn.tumblr.com/'

# blog:      # Your Tumblr blog name (without the tumblr.com i.e. wqxyz if your blog is wqxyz.tumblr.com).
# email:     # The e-mail address used to sign into Tumblr; used for deployment.
# password:  # The password used to sign into Tumblr; used for deployment.
# index:     # The path (relative to root) to the main theme; the theme to be deployed to tumblr; used as the watcher's index.  Defaults to `index.ext`.
# compiler:
#   url:     # The base url to join with urls output via our url syntax.
